#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
利用 API 在坐标原点生成一个 PowerRune，按 TYPE_TO_YOLO_CLASS 中存在的物体
提取其世界坐标（经 FILTER_MAXNUMS 过滤），输出为 generated_code/world_keypoints.hpp。
"""

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from power_rune_client import PowerRuneRenderer
from dataset_config import TYPE_TO_YOLO_CLASS, FILTER_MAXNUMS, CLASS_NAMES_BASE

# ---------------------------------------------------------------------------
# 渲染分辨率（世界坐标与分辨率无关，取方便调试的值即可）
# ---------------------------------------------------------------------------
RENDER_WIDTH = 1280
RENDER_HEIGHT = 1280

# TYPE_TO_YOLO_CLASS 中的物体与扇叶状态的关系：
#   type 0 (R / center_R)   → 始终可见，不依赖扇叶状态
#   type 2 (target)          → 仅当扇叶状态=1（流动箭头）时可见
#   type 3 (arrow)           → 同上，状态=1
#   type 4 (small_activating)→ 仅当扇叶状态=2（小激活）时可见
#
# 我们通过临时改变扇叶 0 的状态来分别采集各类物体的世界坐标。
# 采集完成后扇叶 0 恢复为“亮起”状态（state=3）。
# ---------------------------------------------------------------------------

# 物体类型(type_index) ← 需要的扇叶状态 (None 表示始终可见)
TYPE_TO_REQUIRED_STATE = {
    0: None,   # center_R   – 始终存在
    2: 1,      # target     – 扇叶状态 1
    3: 1,      # arrow      – 扇叶状态 1
    4: 2,      # small_activating – 扇叶状态 2
}


def _extract_world_kps_from_groups(groups, target_types):
    """
    从 render() 返回的 groups 中提取指定 obj_type 的世界坐标。

    参数
    ----
    groups : list
        render() 的第二个返回值，每个元素为
        (object_type, indices, xs, ys,
         world_xs, world_ys, world_zs,
         cam_xs, cam_ys, cam_zs, valids, occludeds)
    target_types : set
        需要采集的物体类型（object_type）

    返回
    ----
    dict : obj_type → list of (x, y, z)
    """
    result = {}
    for group in groups:
        obj_type = group[0]
        if obj_type not in target_types:
            continue

        world_xs = group[4]
        world_ys = group[5]
        world_zs = group[6]

        yolo_cls = TYPE_TO_YOLO_CLASS[obj_type]
        max_num = FILTER_MAXNUMS[yolo_cls]
        n = min(len(world_xs), max_num)

        filtered = []
        for i in range(n):
            filtered.append((float(world_xs[i]), float(world_ys[i]), float(world_zs[i])))
        result[obj_type] = filtered
    return result


def _generate_cpp_header(all_kps, type_to_name):
    """
    生成 C++ 头文件内容。

    参数
    ----
    all_kps : dict
        obj_type → list of (x, y, z)
    type_to_name : dict
        obj_type → 变量名（对应 CLASS_NAMES 去掉颜色后缀）

    返回
    ----
    str
    """
    lines = []
    lines.append("// Auto-generated world keypoints for PowerRune objects.")
    lines.append("// Generated by generate_world_keypoints.py – do not edit by hand.")
    lines.append("")
    lines.append("#pragma once")
    lines.append("")
    lines.append("#include <vector>")
    lines.append("#include <opencv2/core.hpp>")
    lines.append("")
    lines.append("namespace power_rune_keypoints {")
    lines.append("")

    for obj_type in sorted(all_kps.keys()):
        name = type_to_name[obj_type]
        kps = all_kps[obj_type]
        yolo_cls = TYPE_TO_YOLO_CLASS[obj_type]
        max_num = FILTER_MAXNUMS[yolo_cls]
        lines.append(f"// {name}  (object_type={obj_type}, max_keypoints={max_num})")
        lines.append(f"inline const std::vector<cv::Point3f> kps_{name} = {{")
        for x, y, z in kps:
            lines.append(f"    {{ {x:.6f}f, {y:.6f}f, {z:.6f}f }},")
        lines.append("};")
        lines.append("")

    lines.append("}  // namespace power_rune_keypoints")
    return "\n".join(lines)


def main():
    # ---- 1. 创建渲染器与能量机关 ----
    renderer = PowerRuneRenderer(
        logical_width=RENDER_WIDTH,
        logical_height=RENDER_HEIGHT,
        super_sample_factor=1.0,
    )
    renderer.create_power_rune(0.0, 0.0, 0.0)

    # 设置一个基础的相机内参（不影响世界坐标，但渲染必须调用）
    renderer.set_camera(
        1.31280460e03,
        1.31309593e03,
        6.38736364e02,
        5.34133502e02,
        RENDER_WIDTH,
        RENDER_HEIGHT,
        k1=-0.05392145,
        k2=-0.02516686,
        p1=-0.00222499,
        p2=-0.00149047,
        k3=0.43693918,
    )
    # 相机摆放到原点前方，正对机关
    renderer.set_camera_pose(0.0, 0.0, 1.0, 0.0, 0.0, 0.0)

    # ---- 2. 初始化所有扇叶为关闭状态 ----
    for i in range(5):
        renderer.set_fan_state(i, 0)

    # ---- 3. 按需要的扇叶状态分组采集世界坐标 ----
    # state → set of object_types
    state_to_types = {}
    for obj_type, req_state in TYPE_TO_REQUIRED_STATE.items():
        state_to_types.setdefault(req_state, set()).add(obj_type)

    all_kps = {}

    for req_state, target_types in state_to_types.items():
        if req_state is not None:
            # 将扇叶 0 切到需要的状态
            renderer.set_fan_state(0, req_state)

        _, groups = renderer.render()
        kps = _extract_world_kps_from_groups(groups, target_types)
        all_kps.update(kps)

    # ---- 4. 扇叶 0 亮起（状态 3）----
    renderer.set_fan_state(0, 3)

    # ---- 5. 构建 type → 名字映射 ----
    # TYPE_TO_YOLO_CLASS : obj_type → yolo_class
    # CLASS_NAMES_BASE     : [yolo_class] = 名字（无颜色后缀）
    type_to_name = {}
    for obj_type, yolo_cls in TYPE_TO_YOLO_CLASS.items():
        type_to_name[obj_type] = CLASS_NAMES_BASE[yolo_cls]

    # ---- 6. 写入 C++ 头文件 ----
    output_dir = os.path.join(
        os.path.dirname(os.path.abspath(__file__)), "..", "generated_code"
    )
    os.makedirs(output_dir, exist_ok=True)
    output_path = os.path.join(output_dir, "world_keypoints.hpp")

    cpp_code = _generate_cpp_header(all_kps, type_to_name)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(cpp_code)
    print(f"Generated: {output_path}")

    # 打印摘要
    print("\n世界关键点摘要:")
    for obj_type in sorted(all_kps.keys()):
        name = type_to_name[obj_type]
        kps = all_kps[obj_type]
        print(f"  {name} (type={obj_type}): {len(kps)} keypoints")
        for i, (x, y, z) in enumerate(kps):
            print(f"    [{i}] ({x:.6f}, {y:.6f}, {z:.6f})")


if __name__ == "__main__":
    main()