// Auto-generated world keypoints for PowerRune objects.
// Generated by generate_world_keypoints.py – do not edit by hand.

#pragma once

#include <vector>
#include <opencv2/core.hpp>

namespace power_rune_keypoints {

// R  (object_type=0, max_keypoints=8)
inline const std::vector<cv::Point3f> kps_R = {
    { 0.000000f, 0.000000f, -0.166400f },
    { -0.033200f, -0.034200f, -0.166400f },
    { -0.036100f, 0.026800f, -0.166400f },
    { 0.033100f, 0.037400f, -0.166400f },
    { 0.035300f, 0.023700f, -0.166400f },
    { 0.034300f, -0.015000f, -0.166400f },
    { 0.015700f, -0.034200f, -0.166400f },
    { 0.028200f, -0.029100f, -0.166400f },
};

// target  (object_type=2, max_keypoints=9)
inline const std::vector<cv::Point3f> kps_target = {
    { 0.000000f, -0.699600f, 0.000000f },
    { 0.150000f, -0.699600f, 0.000000f },
    { 0.000000f, -0.549600f, 0.000000f },
    { -0.150000f, -0.699600f, 0.000000f },
    { 0.000000f, -0.849600f, 0.000000f },
    { 0.095459f, -0.604141f, 0.000000f },
    { -0.095459f, -0.604141f, 0.000000f },
    { -0.095459f, -0.795059f, 0.000000f },
    { 0.095459f, -0.795059f, 0.000000f },
};

// arrow  (object_type=3, max_keypoints=4)
inline const std::vector<cv::Point3f> kps_arrow = {
    { -0.030000f, -0.504300f, 0.000000f },
    { -0.030000f, -0.174300f, 0.000000f },
    { 0.030000f, -0.174300f, 0.000000f },
    { 0.030000f, -0.504300f, 0.000000f },
};

// small_activating  (object_type=4, max_keypoints=11)
inline const std::vector<cv::Point3f> kps_small_activating = {
    { -0.186946f, -0.540163f, 0.000000f },
    { -0.030496f, -0.505596f, 0.000000f },
    { -0.198401f, -0.331255f, 0.000000f },
    { -0.059535f, -0.175000f, 0.000000f },
    { -0.147558f, -0.731186f, 0.000000f },
    { 0.000000f, -0.850763f, 0.000000f },
    { 0.186946f, -0.540163f, 0.000000f },
    { 0.030496f, -0.505596f, 0.000000f },
    { 0.198401f, -0.331255f, 0.000000f },
    { 0.059535f, -0.175000f, 0.000000f },
    { 0.147558f, -0.731186f, 0.000000f },
};

}  // namespace power_rune_keypoints